#!/usr/bin/env python3
"""
Daily Maya Journal Entry Generator
This script generates a new journal entry for Maya Watson and adds it to journal.html
"""
import os
import sys
import subprocess
import re
from datetime import datetime

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
JOURNAL_PATH = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "journal.html")

def get_today_date():
    """Get today's date in format 'Month DD, YYYY'"""
    return datetime.now().strftime("%B %d, %Y")

def get_git_user():
    """Get git user config for commits"""
    return "github-actions[bot]", "github-actions[bot]@users.noreply.github.com"

def run_git_command(cmd, cwd=None):
    """Run a git command and return result"""
    result = subprocess.run(cmd, shell=True, cwd=cwd, capture_output=True, text=True)
    if result.returncode != 0:
        print(f"Command failed: {cmd}")
        print(f"stdout: {result.stdout}")
        print(f"stderr: {result.stderr}")
    return result

def generate_journal_entry():
    """Generate a Maya-style journal entry for today"""
    today_str = datetime.now().strftime("%B %d, %Y")
    
    # This is where we'd call an LLM to generate the content
    # For now, we'll use a template that can be filled in
    # In production, this would call an LLM API
    
    # For now, we'll create a placeholder that can be replaced
    # In production, this would call an LLM API
    
    # For now, we'll just create a placeholder entry
    # The actual content should be generated by an LLM
    entry = f'''            <div class="post">
                <div class="post-date">{datetime.now().strftime("%B %d, %Y")}</div>
                <h3>Daily Entry - {datetime.now().strftime("%B %d, %Y")}</h3>
                <p>This entry was auto-generated. Replace with actual Maya content.</p>
                <p><em>— Placeholder entry</em></p>
            </div>

'''
    return entry

def add_entry_to_journal(new_entry):
    """Add a new entry to the top of the journal-posts section"""
    with open('journal.html', 'r', encoding='utf-8') as f:
        content = f.read()
    
    # Find the insertion point - right after <div class="container"> inside journal-posts
    insert_marker = '<section class="journal-posts">\n        <div class="container">'
    insert_pos = content.find(insert_marker)
    
    if insert_pos == -1:
        # Try alternative pattern
        insert_pos = content.find('<section class="journal-posts">')
        if insert_pos != -1:
            # Find the container div
            container_start = content.find('<div class="container">', insert_pos)
            if container_start != -1:
                insert_pos = content.find('>', container_start) + 1
    
    if insert_pos == -1:
        print("ERROR: Could not find insertion point")
        return False
    
    insert_pos += len('<section class="journal-posts">\n        <div class="container">')
    
    # Create new entry
    today_str = datetime.now().strftime("%B %d, %Y")
    new_entry = f'''            <div class="post">
                <div class="post-date">{datetime.now().strftime("%B %d, %Y")}</div>
                <h3>Daily Entry - {datetime.now().strftime("%B %d, %Y")}</h3>
                <p>This entry was auto-generated. Replace with actual Maya content.</p>
                <p><em>— Placeholder entry</em></p>
            </div>

'''
    
    # Insert the new entry
    new_content = content[:insert_pos] + '\n' + new_entry + content[insert_pos:]
    
    with open('journal.html', 'w', encoding='utf-8') as f:
        f.write(content)
    
    return True

def git_commit_and_push():
    """Commit and push changes"""
    try:
        # Configure git
        subprocess.run(["git", "config", "user.name", "github-actions[bot]"], check=True)
        subprocess.run(["git", "config", "user.email", "github-actions[bot]@users.noreply.github.com"], check=True)
        
        # Add and commit
        subprocess.run(["git", "add", "journal.html"], check=True)
        result = subprocess.run(["git", "commit", "-m", f"Add journal entry for {datetime.now().strftime('%Y-%m-%d')}"], capture_output=True, text=True)
        if result.returncode != 0 and "nothing to commit" not in result.stderr:
            print(f"Commit failed: {result.stderr}")
            return False
        
        # Push
        subprocess.run(["git", "push", "origin", "main"], check=True)
        return True
    except subprocess.CalledProcessError as e:
        print(f"Git error: {e}")
        return False

def main():
    print(f"[{datetime.now()}] Generating journal entry...")
    
    # Check if there are uncommitted changes
    result = subprocess.run(["git", "status", "--porcelain"], capture_output=True, text=True)
    if result.stdout.strip():
        print("Working tree not clean, committing changes...")
        subprocess.run(["git", "add", "."], check=True)
        subprocess.run(["git", "commit", "-m", f"Auto-commit before daily journal"], check=True)
        subprocess.run(["git", "push", "origin", "main"], check=True)
    
    # Generate and add entry
    if not generate_journal_entry():
        return False
    
    # Commit and push
    if not git_commit_and_push():
        return False
    
    print(f"[{datetime.now()}] Journal entry added successfully")
    return True

if __name__ == "__main__":
    success = main()
    sys.exit(0 if success else 1)